#!/bin/sh

set -e

basedir=/usr/lib/jvm/java-17-openjdk-amd64
multiarch=x86_64-linux-gnu
jdirname=java-17-openjdk-amd64
etcdir=/etc/java-17-openjdk

case "$1" in
purge)
    if [ -z "$jdirname" ] || [ -z "$etcdir" ]; then
	echo >&2 "$(basename $0): Internal error"
	exit 1
    fi
    rm -f $basedir/lib/*/classes.jsa

    # removals of config files in /etc is handled by dpkg

    # XXX should remove /etc/.java ???
    ;;
esac


